### PR TITLE
Fix mixed types in slice binding causing crashes

### LINKED ISSUE #532: db.QueryContext crashes the server with SIGSEGV when invalid args are sent
### Current behaviour:
go-duckdb crashes the server when db.QueryContext is called with named args of mixed type like `[]any{"hello this is text", 2}`. 
### Expected behaviour:
Instead of crashing, it should return a proper handleable error.

### go-duckdb Version
v2.3.6

### Minimal Reproducible Example

[https://replit.com/@AyushKaithwas1/named-args-issue#main.go](https://replit.com/@AyushKaithwas1/named-args-issue#main.go)

### Error log:

```
--- DuckDB: mixed-type slice bound to named arg (expect potential segfault) ---
SIGSEGV: segmentation violation
PC=0x10fa290 m=3 sigcode=1 addr=0x0
signal arrived during cgo execution

goroutine 16 gp=0xc00009c8c0 m=3 mp=0xc000059008 [syscall]:
runtime.cgocall(0x860290, 0xc0000bb5b8)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/cgocall.go:167 +0x4b fp=0xc0000bb590 sp=0xc0000bb558 pc=0x7721eb
github.com/duckdb/duckdb-go-bindings/linux-amd64._Cfunc_duckdb_bind_value(0x7f8b10005a40, 0x1, 0x0)
    _cgo_gotypes.go:1399 +0x46 fp=0xc0000bb5b8 sp=0xc0000bb590 pc=0x7dd8c6
github.com/duckdb/duckdb-go-bindings/linux-amd64.BindValue.func1(...)
    /home/runner/workspace/gopath/pkg/mod/github.com/duckdb/duckdb-go-bindings/linux-amd64@v0.1.12/bindings.go:1323
github.com/duckdb/duckdb-go-bindings/linux-amd64.BindValue({0x7f8b10005a40}, 0x1, {0x0})
    /home/runner/workspace/gopath/pkg/mod/github.com/duckdb/duckdb-go-bindings/linux-amd64@v0.1.12/bindings.go:1323 +0x7c fp=0xc0000bb5f8 sp=0xc0000bb5b8 pc=0x7e4efc
github.com/marcboeker/go-duckdb/v2.(*Stmt).tryBindComplexValue(0xc0000101f8, {{0x225d823, 0x8}, 0x1, {0x2225fc0, 0xc0000101c8}}, 0x0)
    /home/runner/workspace/gopath/pkg/mod/github.com/marcboeker/go-duckdb/v2@v2.3.6/statement.go:291 +0x25e fp=0xc0000bb6c8 sp=0xc0000bb5f8 pc=0x82ddde
github.com/marcboeker/go-duckdb/v2.(*Stmt).bindComplexValue(0xc00009c8c0?, {{0x225d823, 0x8}, 0x1, {0x2225fc0, 0xc0000101c8}}, 0x754689?, 0x687d8?, {0x225d5d0, 0x7})
    /home/runner/workspace/gopath/pkg/mod/github.com/marcboeker/go-duckdb/v2@v2.3.6/statement.go:299 +0x33d fp=0xc0000bb768 sp=0xc0000bb6c8 pc=0x82e29d
github.com/marcboeker/go-duckdb/v2.(*Stmt).bindValue(0xc0000101f8, {{0x225d823, 0x8}, 0x1, {0x2225fc0, 0xc0000101c8}}, 0x0)
    /home/runner/workspace/gopath/pkg/mod/github.com/marcboeker/go-duckdb/v2@v2.3.6/statement.go:410 +0xe35 fp=0xc0000bb8f8 sp=0xc0000bb768 pc=0x82f155
github.com/marcboeker/go-duckdb/v2.(*Stmt).bind(0xc0000101f8, {0xc00003eb70, 0x1, 0x2244d20?})
    /home/runner/workspace/gopath/pkg/mod/github.com/marcboeker/go-duckdb/v2@v2.3.6/statement.go:439 +0x25c fp=0xc0000bba88 sp=0xc0000bb8f8 pc=0x82f63c
github.com/marcboeker/go-duckdb/v2.(*Stmt).execute(0xc0000101f8, {0x229ef10, 0xc0000a8000}, {0xc00003eb70?, 0xc000068a01?, 0xc000068b20?})
    /home/runner/workspace/gopath/pkg/mod/github.com/marcboeker/go-duckdb/v2@v2.3.6/statement.go:540 +0x4a fp=0xc0000bbab8 sp=0xc0000bba88 pc=0x83014a
github.com/marcboeker/go-duckdb/v2.(*Stmt).QueryContext(0xc0000101f8, {0x229ef10?, 0xc0000a8000?}, {0xc00003eb70?, 0x6f?, 0x0?})
    /home/runner/workspace/gopath/pkg/mod/github.com/marcboeker/go-duckdb/v2@v2.3.6/statement.go:501 +0x34 fp=0xc0000bbb30 sp=0xc0000bbab8 pc=0x830034
github.com/marcboeker/go-duckdb/v2.(*Conn).QueryContext(0xc000072260, {0x229ef10, 0xc0000a8000}, {0x2269d87?, 0x0?}, {0xc00003eb70, 0x1, 0x1})
    /home/runner/workspace/gopath/pkg/mod/github.com/marcboeker/go-duckdb/v2@v2.3.6/connection.go:90 +0xd7 fp=0xc0000bbbb8 sp=0xc0000bbb30 pc=0x829577
database/sql.ctxDriverQuery({0x229ef10?, 0xc0000a8000?}, {0x7f8b198cba18?, 0xc000072260?}, {0x0?, 0x0?}, {0x2269d87?, 0x0?}, {0xc00003eb70, 0x1, ...})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/database/sql/ctxutil.go:48 +0xd7 fp=0xc0000bbc40 sp=0xc0000bbbb8 pc=0x7cd637
database/sql.(*DB).queryDC.func1()
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/database/sql/sql.go:1786 +0x159 fp=0xc0000bbd00 sp=0xc0000bbc40 pc=0x7d4539
database/sql.withLock({0x229e920, 0xc0000b4000}, 0xc000055e60)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/database/sql/sql.go:3572 +0x71 fp=0xc0000bbd40 sp=0xc0000bbd00 pc=0x7d8871
database/sql.(*DB).queryDC(0xc000055f38?, {0x229ef10, 0xc0000a8000}, {0x0, 0x0}, 0xc0000b4000, 0xc000014230, {0x2269d87, 0x6f}, {0xc000014210, ...})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/database/sql/sql.go:1781 +0x1de fp=0xc0000bbef0 sp=0xc0000bbd40 pc=0x7d3d7e
database/sql.(*Conn).QueryContext(0xc00007e140, {0x229ef10, 0xc0000a8000}, {0x2269d87, 0x6f}, {0xc000014210, 0x1, 0x1})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/database/sql/sql.go:2037 +0xc5 fp=0xc0000bbf60 sp=0xc0000bbef0 pc=0x7d50c5
main.callQueryWithMixedArg.func1()
    /home/runner/workspace/main.go:121 +0x79 fp=0xc0000bbfe0 sp=0xc0000bbf60 pc=0x8483f9
runtime.goexit({})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc0000bbfe8 sp=0xc0000bbfe0 pc=0x77b641
created by main.callQueryWithMixedArg in goroutine 1
    /home/runner/workspace/main.go:119 +0x26f

goroutine 1 gp=0xc000002380 m=nil [sync.WaitGroup.Wait]:
runtime.gopark(0xc000067d30?, 0x71b774?, 0xa0?, 0x2?, 0xc0000aa0b8?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:435 +0xce fp=0xc000067cd0 sp=0xc000067cb0 pc=0x77474e
runtime.goparkunlock(...)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:441
runtime.semacquire1(0xc0000121e8, 0x0, 0x1, 0x0, 0x18)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/sema.go:188 +0x21d fp=0xc000067d38 sp=0xc000067cd0 pc=0x7563fd
sync.runtime_SemacquireWaitGroup(0xc000080300?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/sema.go:110 +0x25 fp=0xc000067d70 sp=0xc000067d38 pc=0x775ac5
sync.(*WaitGroup).Wait(0x2245be0?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/sync/waitgroup.go:118 +0x48 fp=0xc000067d98 sp=0xc000067d70 pc=0x781408
main.callQueryWithMixedArg({0x229ef10, 0xc0000a8000}, 0xc00007e140)
    /home/runner/workspace/main.go:123 +0x27c fp=0xc000067ec0 sp=0xc000067d98 pc=0x847fdc
main.main()
    /home/runner/workspace/main.go:28 +0x105 fp=0xc000067f50 sp=0xc000067ec0 pc=0x8476e5
runtime.main()
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:283 +0x28b fp=0xc000067fe0 sp=0xc000067f50 pc=0x742f8b
runtime.goexit({})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x77b641

goroutine 2 gp=0xc000002e00 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:435 +0xce fp=0xc000052fa8 sp=0xc000052f88 pc=0x77474e
runtime.goparkunlock(...)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:441
runtime.forcegchelper()
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:348 +0xb3 fp=0xc000052fe0 sp=0xc000052fa8 pc=0x7432d3
runtime.goexit({})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x77b641
created by runtime.init.7 in goroutine 1
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:336 +0x1a

goroutine 3 gp=0xc000003340 m=nil [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:435 +0xce fp=0xc000053780 sp=0xc000053760 pc=0x77474e
runtime.goparkunlock(...)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:441
runtime.bgsweep(0xc00001e100)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgcsweep.go:276 +0x94 fp=0xc0000537c8 sp=0xc000053780 pc=0x72e434
runtime.gcenable.gowrap1()
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgc.go:204 +0x25 fp=0xc0000537e0 sp=0xc0000537c8 pc=0x722b05
runtime.goexit({})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc0000537e8 sp=0xc0000537e0 pc=0x77b641
created by runtime.gcenable in goroutine 1
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgc.go:204 +0x66

goroutine 4 gp=0xc000003500 m=nil [GC scavenge wait]:
runtime.gopark(0xc00001e100?, 0x229c470?, 0x1?, 0x0?, 0xc000003500?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:435 +0xce fp=0xc000053f78 sp=0xc000053f58 pc=0x77474e
runtime.goparkunlock(...)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:441
runtime.(*scavengerState).park(0x2f83f20)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000053fa8 sp=0xc000053f78 pc=0x72bee9
runtime.bgscavenge(0xc00001e100)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000053fc8 sp=0xc000053fa8 pc=0x72c45c
runtime.gcenable.gowrap2()
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgc.go:205 +0x25 fp=0xc000053fe0 sp=0xc000053fc8 pc=0x722aa5
runtime.goexit({})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x77b641
created by runtime.gcenable in goroutine 1
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgc.go:205 +0xa5

goroutine 5 gp=0xc000003dc0 m=nil [finalizer wait]:
runtime.gopark(0x1b8?, 0xc000002380?, 0x1?, 0x23?, 0xc000052688?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:435 +0xce fp=0xc000052630 sp=0xc000052610 pc=0x77474e
runtime.runfinq()
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mfinal.go:196 +0x107 fp=0xc0000527e0 sp=0xc000052630 pc=0x721ac7
runtime.goexit({})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x77b641
created by runtime.createfing in goroutine 1
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mfinal.go:166 +0x3d

goroutine 6 gp=0xc00009c000 m=nil [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:435 +0xce fp=0xc000054718 sp=0xc0000546f8 pc=0x77474e
runtime.chanrecv(0xc000028150, 0x0, 0x1)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/chan.go:664 +0x445 fp=0xc000054790 sp=0xc000054718 pc=0x714485
runtime.chanrecv1(0x0?, 0x0?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/chan.go:506 +0x12 fp=0xc0000547b8 sp=0xc000054790 pc=0x714032
runtime.unique_runtime_registerUniqueMapCleanup.func2(...)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgc.go:1797
runtime.unique_runtime_registerUniqueMapCleanup.gowrap1()
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgc.go:1800 +0x2f fp=0xc0000547e0 sp=0xc0000547b8 pc=0x725a4f
runtime.goexit({})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc0000547e8 sp=0xc0000547e0 pc=0x77b641
created by unique.runtime_registerUniqueMapCleanup in goroutine 1
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/mgc.go:1795 +0x79

goroutine 7 gp=0xc00009c540 m=nil [select]:
runtime.gopark(0xc000054f88?, 0x2?, 0x0?, 0x0?, 0xc000054f84?)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/proc.go:435 +0xce fp=0xc000054e18 sp=0xc000054df8 pc=0x77474e
runtime.selectgo(0xc000054f88, 0xc000054f80, 0x0?, 0x0, 0x0?, 0x1)
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/select.go:351 +0x837 fp=0xc000054f50 sp=0xc000054e18 pc=0x755357
database/sql.(*DB).connectionOpener(0xc000096750, {0x229eea0, 0xc00009e050})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/database/sql/sql.go:1261 +0x87 fp=0xc000054fb8 sp=0xc000054f50 pc=0x7d0e67
database/sql.OpenDB.gowrap1()
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/database/sql/sql.go:841 +0x28 fp=0xc000054fe0 sp=0xc000054fb8 pc=0x7cf9a8
runtime.goexit({})
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc000054fe8 sp=0xc000054fe0 pc=0x77b641
created by database/sql.OpenDB in goroutine 1
    /home/runner/workspace/gopath/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/database/sql/sql.go:841 +0x130

rax    0x7f8b198b8ca0
rbx    0x7f8b198b8ce0
rcx    0x6e6f697461636f6c
rdx    0x8
rdi    0x7f8b198b8ce0
rsi    0x0
rbp    0x0
rsp    0x7f8b198b8c78
r8     0xc000059008
r9     0x0
r10    0x82df00
r11    0x0
r12    0x0
r13    0x7f8b198b8ca0
r14    0x1
r15    0xc0000562f0
rip    0x10fa290
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

### PR DESCRIPTION
**Pull request by mlafeldt**
Validates that all non-null elements in a slice have the same type during binding to prevent crashes when mixed types are encountered.

Fixes #532

### CODE REVIEW

File: statement_test.go [hunk 1]
```diff
@@ -844,3 +844,21 @@ func TestDriverValuer(t *testing.T) {
...
 	require.Contains(t, err.Error(), "unsupported data type: UUID")
 }
+
+func TestMixedTypeSliceBinding(t *testing.T) {
+	db := openDbWrapper(t, ``)
+	defer closeDbWrapper(t, db)
+
+	createTable(t, db, `CREATE TABLE mixed_slice_test (foo TEXT)`)
+	_, err := db.Exec(`INSERT INTO mixed_slice_test VALUES ('hello this is text'), ('other')`)
+	require.NoError(t, err)
```
Comment (taniabogatsch) [inline statement_test.go:854]: Let's also add a test for the same-type case (with `any`)? E.g., `[]any{"hello this is text", "other"}`.

File: statement_test.go [hunk 2]
```diff
@@ -844,3 +844,21 @@ func TestDriverValuer(t *testing.T) {
...
+
+	mixedSlice := []any{"hello this is text", 2}
+
+	_, err = db.Query("FROM mixed_slice_test WHERE foo IN ?", mixedSlice)
+	require.ErrorContains(t, err, "mixed types in slice at index 0: cannot bind BIGINT and VARCHAR together: index: 1")
```
Comment (taniabogatsch) [inline statement_test.go:859]: nit: maybe we can change this to `mixed types in slice: cannot bind BIGINT (index 1) and VARCHAR (index 0)`? 🤔

File: value.go [hunk 3]
```diff
@@ -289,6 +289,20 @@ func tryGetMappedSliceValue[T any](val T, isArray bool, sliceLength int) (mappin
 	if elementLogicType.Ptr == nil {
 		return elementLogicType, mapping.Value{}, unsupportedTypeError(reflect.TypeOf(val).Name())
 	}
+
+	// Validate that all non-null elements have the same type to prevent mixed-type crashes
+	expectedType := mapping.GetTypeId(elementLogicType)
+	for i, lt := range childLogicTypes {
```
Comment (taniabogatsch) [inline value.go:295]: I wonder if we can move this up into the `range vSlice` loop? Then, we can early-out there already (and don't need to process all parameters first), if we encounter a mismatch.

File: value.go [hunk 4]
```diff
@@ -289,6 +289,20 @@ func tryGetMappedSliceValue[T any](val T, isArray bool, sliceLength int) (mappin
...
+		if lt.Ptr != nil {
+			currentType := mapping.GetTypeId(lt)
```
Comment (taniabogatsch) [inline value.go:297]: `GetTypeId` is only the top-level type - thus, I think we need to make sure we compare types recursively here (using their logical types to get child-type IDs). The following test still fails:

```Go
	mixedSlice := [][]any{{"hello this is text"}, {2}}
	_, err = db.Query("FROM mixed_slice_test WHERE foo IN ?", mixedSlice)
```

**Review by taniabogatsch — COMMENTED** [review]
Thanks for looking into this! Left some comments. :)

File: statement_test.go (hunk 1 above)
Comment (mlafeldt) [reply statement_test.go:854]: Done

**Comment by mlafeldt** [comment]
@taniabogatsch Thanks for the review. I've addressed all your comments. PTAL.

**Review by taniabogatsch — APPROVED** [review]
